### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by PurplePachyderm** [PurplePachyderm/browser-homepage#1]
**Main features:**
- [x] Animation to hide/show websites list
- [x] Functionnal clock
- [ ] Weather widget using API
- [ ] RSS feed

**Minor features:**
- [ ] Countdown to custom date
- [ ] Randomize backgrounds
- [ ] Replace checkbox with Ctrl shortcut to open in new tab
- [ ] Link Github repo

**Comment by PurplePachyderm** [comment]
Replaced with "Features" project
